# Generated by Django 5.2.17 on 2026-09-15 15:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteIntegracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(choices=[('SISTEMA', 'Sistema'), ('USUARIO', 'Usuario')], default='SISTEMA', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'agentes_integracion',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoTributario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('uuid_operacion', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id_venta_origen', models.CharField(help_text='ID de venta en el sistema privado (correlación)', max_length=100)),
                ('tipo_documento', models.IntegerField(choices=[(33, 'Factura'), (34, 'Factura Exenta'), (35, 'Boleta Exenta'), (38, 'Boleta'), (39, 'Boleta'), (41, 'Boleta Honorarios'), (46, 'Factura Compra'), (52, 'Guía de Despacho'), (56, 'Nota Débito'), (61, 'Nota Crédito')], default=39)),
                ('folio', models.IntegerField(blank=True, null=True)),
                ('track_id', models.CharField(blank=True, max_length=100, null=True)),
                ('rut_emisor', models.CharField(max_length=12)),
                ('rut_receptor', models.CharField(max_length=12)),
                ('razon_social_receptor', models.CharField(blank=True, max_length=200, null=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('pdf_url', models.CharField(blank=True, max_length=500, null=True)),
                ('xml_url', models.CharField(blank=True, max_length=500, null=True)),
                ('respuesta_sii_json', models.JSONField(blank=True, null=True)),
                ('codigo_estado_sii', models.IntegerField(blank=True, null=True)),
                ('glosa_estado_sii', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_referencia', models.IntegerField(blank=True, null=True)),
                ('fecha_referencia', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.CharField(blank=True, max_length=250, null=True)),
                ('intentos', models.IntegerField(default=0)),
                ('proximo_reintento', models.DateTimeField(blank=True, null=True)),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('documento_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='documentos_referenciados', to='integrations.documentotributario')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='configurations.empresa')),
            ],
            options={
                'verbose_name': 'Documento Tributario',
                'verbose_name_plural': 'Documentos Tributarios',
                'db_table': 'documentos_tributarios',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.IntegerField()),
                ('nombre_producto', models.CharField(max_length=200)),
                ('codigo_producto', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_linea', models.DecimalField(decimal_places=2, max_digits=12)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='integrations.documentotributario')),
            ],
            options={
                'db_table': 'detalles_documento',
                'ordering': ['documento_id', 'linea'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoEstadoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='integrations.agenteintegracion')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_estados', to='integrations.documentotributario')),
            ],
            options={
                'db_table': 'historico_estados_documento',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='LogConsultaAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('idempotency_key', models.UUIDField(blank=True, null=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('metodo_http', models.CharField(max_length=10)),
                ('codigo_respuesta_http', models.IntegerField(blank=True, null=True)),
                ('payload_enviado', models.JSONField(blank=True, null=True)),
                ('respuesta_recibida', models.JSONField(blank=True, null=True)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('duracion_ms', models.IntegerField(blank=True, null=True)),
                ('ip_origen', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('agente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_api', to='integrations.agenteintegracion')),
            ],
            options={
                'db_table': 'logs_consultas_api',
                'ordering': ['-fecha_consulta'],
            },
        ),
        migrations.CreateModel(
            name='LogConsultaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('proveedor_ia', models.CharField(max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('endpoint', models.CharField(blank=True, max_length=255, null=True)),
                ('prompt_enviado', models.TextField(blank=True, null=True)),
                ('respuesta_recibida', models.TextField(blank=True, null=True)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('tokens_prompt', models.IntegerField(blank=True, null=True)),
                ('tokens_completado', models.IntegerField(blank=True, null=True)),
                ('duracion_ms', models.IntegerField(blank=True, null=True)),
                ('codigo_respuesta_http', models.IntegerField(blank=True, null=True)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('metadata_json', models.JSONField(blank=True, null=True)),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_ia', to='integrations.agenteintegracion')),
            ],
            options={
                'db_table': 'logs_consultas_ia',
                'ordering': ['-fecha_consulta'],
            },
        ),
        migrations.AddIndex(
            model_name='documentotributario',
            index=models.Index(fields=['empresa', 'estado', '-fecha_creacion'], name='ix_doc_empresa_estado'),
        ),
        migrations.AddIndex(
            model_name='documentotributario',
            index=models.Index(fields=['track_id'], name='ix_doc_track_id'),
        ),
        migrations.AddConstraint(
            model_name='documentotributario',
            constraint=models.UniqueConstraint(fields=('empresa', 'id_venta_origen', 'tipo_documento'), name='uq_empresa_venta_tipo'),
        ),
        migrations.AddConstraint(
            model_name='documentotributario',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['PENDIENTE', 'ENVIADO', 'ACEPTADO', 'RECHAZADO', 'ANULADO', 'ERROR'])), name='chk_doc_estado'),
        ),
        migrations.AddConstraint(
            model_name='documentotributario',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_documento__in', [33, 34, 35, 38, 39, 41, 46, 52, 56, 61])), name='chk_doc_tipo'),
        ),
        migrations.AddConstraint(
            model_name='detalledocumento',
            constraint=models.UniqueConstraint(fields=('documento', 'linea'), name='uq_detalle_linea'),
        ),
        migrations.AddIndex(
            model_name='historicoestadodocumento',
            index=models.Index(fields=['documento', '-fecha_cambio'], name='ix_hist_documento'),
        ),
        migrations.AddConstraint(
            model_name='historicoestadodocumento',
            constraint=models.CheckConstraint(condition=models.Q(('estado_nuevo__in', ['PENDIENTE', 'ENVIADO', 'ACEPTADO', 'RECHAZADO', 'ANULADO', 'ERROR'])), name='chk_hist_estado'),
        ),
        migrations.AddConstraint(
            model_name='logconsultaapi',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('idempotency_key',), name='uq_log_api_idempotency'),
        ),
    ]
