# Generated by Django 5.2.17 on 2026-08-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoTributario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_venta', models.CharField(help_text='ID interno de la venta en The Cloe', max_length=50, unique=True)),
                ('folio', models.IntegerField(blank=True, help_text='Folio asignado por el SII vía SimpleAPI', null=True)),
                ('tipo_documento', models.IntegerField(default=39, help_text='Tipo de documento SII (39 = Boleta)')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EMITIDO', 'Emitido'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20)),
                ('respuesta_sii', models.JSONField(blank=True, help_text='Respuesta cruda del SII / SimpleAPI', null=True)),
                ('mensaje_error', models.TextField(blank=True, help_text='Mensaje de error si el estado es RECHAZADO', null=True)),
                ('monto_total', models.DecimalField(blank=True, decimal_places=2, help_text='Monto total de la venta', max_digits=12, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento Tributario',
                'verbose_name_plural': 'Documentos Tributarios',
                'db_table': 'documentos_tributarios',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LogConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_consulta', models.CharField(choices=[('EMISION', 'Emisión de boleta'), ('CONSULTA', 'Consulta de estado'), ('REPORTE', 'Generación de reporte')], max_length=20)),
                ('id_venta_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('parametros', models.JSONField(blank=True, null=True)),
                ('respuesta', models.JSONField(blank=True, null=True)),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'log_consultas',
                'ordering': ['-fecha_consulta'],
            },
        ),
    ]
