# Generated by Django 5.2.17 on 2026-08-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionIntegracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=200)),
                ('timbrado', models.CharField(blank=True, help_text='Número de timbrado vigente', max_length=20, null=True)),
                ('prefijo_folio', models.CharField(default='F', help_text='Prefijo para los folios generados', max_length=10)),
                ('ambiente', models.CharField(choices=[('produccion', 'Producción'), ('testing', 'Testing / Homologación')], default='produccion', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'configuracion_integracion',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
