# Generated by Django 5.2.17 on 2026-09-15 15:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('rut_emisor', models.CharField(max_length=12, unique=True, verbose_name='RUT emisor')),
                ('razon_social', models.CharField(max_length=200)),
                ('nombre_fantasia', models.CharField(blank=True, max_length=200, null=True)),
                ('giro', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('comuna', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'db_table': 'empresas',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='CertificadoDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('archivo_pfx_url', models.CharField(blank=True, help_text='Referencia al archivo; el binario NO va en BD', max_length=500, null=True)),
                ('password_cifrada', models.CharField(blank=True, help_text='Cifrado AES-256 en la aplicación, NUNCA en claro', max_length=500, null=True)),
                ('emisor', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_expiracion', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='configurations.empresa')),
            ],
            options={
                'db_table': 'certificados_digitales',
                'ordering': ['fecha_expiracion'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ambiente', models.CharField(choices=[('produccion', 'Producción'), ('testing', 'Testing / Homologación')], default='testing', max_length=20)),
                ('timbrado', models.CharField(blank=True, max_length=20, null=True)),
                ('prefijo_folio', models.CharField(default='F', max_length=10)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('certificado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='configurations.certificadodigital')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones', to='configurations.empresa')),
            ],
            options={
                'db_table': 'configuraciones_empresa',
                'ordering': ['-fecha_creacion'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('empresa', 'ambiente'), name='uq_config_empresa_ambiente_activa')],
            },
        ),
    ]
