# Generated by Django 5.2.17 on 2026-09-15 16:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configurations', '0001_initial'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sale_id', models.CharField(max_length=100, unique=True)),
                ('document_type', models.CharField(choices=[('BOLETA', 'Boleta'), ('INVOICE', 'Factura')], max_length=20)),
                ('issued_at', models.DateTimeField()),
                ('payment_method', models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia'), ('OTHER', 'Otro')], default='CASH', max_length=20)),
                ('status', models.CharField(choices=[('RECEIVED', 'Recibida'), ('QUEUED', 'En cola'), ('PROCESSING', 'Procesando'), ('EMITTED', 'Emitida'), ('FAILED', 'Fallida')], default='RECEIVED', max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cliente_rut', models.CharField(blank=True, max_length=12, null=True)),
                ('cliente_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('cliente_direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('cliente_comuna', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente_ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('error_mensaje', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venta', to='integrations.documentotributario')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='configurations.empresa')),
            ],
            options={
                'db_table': 'ventas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linea', models.IntegerField()),
                ('codigo_producto', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuesto', models.CharField(choices=[('IVA', 'IVA'), ('EXEMPT', 'Exento')], default='IVA', max_length=10)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sales.venta')),
            ],
            options={
                'db_table': 'detalles_venta',
                'ordering': ['venta_id', 'linea'],
                'constraints': [models.UniqueConstraint(fields=('venta', 'linea'), name='uq_detalle_venta_linea')],
            },
        ),
    ]
