# Generated by Django 5.2.17 on 2026-08-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CredencialSimpleAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo de estas credenciales', max_length=100)),
                ('api_key', models.CharField(help_text='API Key para SimpleAPI', max_length=255)),
                ('base_url', models.URLField(default='https://api.simpleapi.cl/api/v1', help_text='URL base de la API de SimpleAPI')),
                ('activa', models.BooleanField(default=True, help_text='Indica si estas credenciales están activas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'credenciales_simpleapi',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
