# Generated by Django 5.2.17 on 2026-09-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='ID único de la sesión del chatbot', max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_count', models.IntegerField(default=0, help_text='Cantidad total de mensajes en la sesión')),
                ('last_message', models.TextField(blank=True, help_text='Último mensaje recibido')),
                ('last_response', models.TextField(blank=True, help_text='Última respuesta del bot')),
            ],
            options={
                'verbose_name': 'Sesión Chatbot',
                'verbose_name_plural': 'Sesiones Chatbot',
                'ordering': ['-created_at'],
            },
        ),
    ]
